package com.msi.tough.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdsAvailabilityZone generated by hbm2java
 */
@Entity
@Table(name = "availability_zone")
public class AvailabilityZoneBean {

	@Id
	@Column(name = "availability_zone")
	private String availabilityZone;

	@Column(name = "bak_window")
	private String preferredBackupWindow;

	@Column(name = "mntn_window")
	private String preferredMaintenanceWindow;

	@Column(name = "cloud_type")
	private String cloudType;

	@Column(name = "def")
	private Boolean default_;

	public String getAvailabilityZone() {
		return availabilityZone;
	}

	public String getCloudType() {
		return cloudType;
	}

	public Boolean getDefault_() {
		return default_;
	}

	public String getPreferredBackupWindow() {
		return preferredBackupWindow;
	}

	public String getPreferredMaintenanceWindow() {
		return preferredMaintenanceWindow;
	}

	public void setAvailabilityZone(String availabilityZone) {
		this.availabilityZone = availabilityZone;
	}

	public void setCloudType(String cloudType) {
		this.cloudType = cloudType;
	}

	public void setDefault_(Boolean default_) {
		this.default_ = default_;
	}

	public void setPreferredBackupWindow(String preferredBackupWindow) {
		this.preferredBackupWindow = preferredBackupWindow;
	}

	public void setPreferredMaintenanceWindow(String preferredMaintenanceWindow) {
		this.preferredMaintenanceWindow = preferredMaintenanceWindow;
	}

}
