package com.msi.tough.model;

// Generated May 10, 2011 9:13:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdsEvent generated by hbm2java
 */
@Entity
@Table(name = "event_log")
public class EventLogBean {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	private long userId;
	private String message;
	private String type;
	private Date createdTime;

	public Date getCreatedTime() {
		return createdTime;
	}

	public long getId() {
		return id;
	}

	public String getMessage() {
		return message;
	}

	public String getType() {
		return type;
	}

	public long getUserId() {
		return userId;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}
}
