package com.msi.tough.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdsAvailabilityZone generated by hbm2java
 */
@Entity
@Table(name = "system_defaults")
public class SystemDefaultsBean {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Column(name = "type")
	private String type;

	@Column(name = "key_name")
	private String key;

	@Column(name = "key_value")
	private String value;

	@Column(name = "def")
	private Boolean def;

	public Boolean getDef() {
		return def;
	}

	public long getId() {
		return id;
	}

	public String getKey() {
		return key;
	}

	public String getType() {
		return type;
	}

	public String getValue() {
		return value;
	}

	public void setDef(Boolean def) {
		this.def = def;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
