package com.msi.tough.model.rds;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.msi.tough.model.AccountBean;

/**
 * RdsDbinstance generated by hbm2java
 */

@Entity
@Table(name = "rds_dbinstance")
public class RdsDbinstance {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rds_dbinstance_id")
	private long id;

	@ManyToOne
	private AccountBean account;

	@Column(name = "userId")
	private long userId;

	@Column(name = "db_instance_identifier", length = 63, nullable = false)
	private String dbinstanceId;

	@Column(name = "instance_id")
	private String instanceId;
	private String sourceDbinstanceId;
	private String dbinstanceClass;
	private Integer allocatedStorage;
	private Date instanceCreateTime;
	private String dbinstanceStatus;
	private String engine;
	private String engineVersion;
	private String availabilityZone;
	private Boolean multiAz;
	private String address;
	private String internalIP;
	private Integer port;
	private String masterUsername;
	private String masterUserPassword;
	private String dbName;
	private Boolean autoMinorVersionUpgrade;
	private Boolean allowMajorVersionUpgrade;
	private Integer backupRetentionPeriod;
	private Date latestRestorableTime;
	private String preferredBackupWindow;
	private String preferredMaintenanceWindow;
	private String dbParameterGroup;
	private String dbParameterGroupStatus;
	private long dbParameterGroupUserId;
	private String volumeId;
	private String snapshotId;
	private String licenseModel;
	private Boolean read_only;
	private String finalSnapshotId;
	private String securityGroup;
	private String securityGroupId;

	@ElementCollection
	@CollectionTable(name = "rds_replications")
	@Column(name = "replications")
	private List<String> replicas;

	@ManyToMany
	@JoinTable(name = "rds_pending_reboot_params")
	private List<RdsParameter> pendingRebootParameters;

	@ManyToMany
	@JoinTable(name = "rds_instance_rds_security_group_membership")
	private List<RdsDbsecurityGroup> securityGroups;

	@ManyToOne
	@JoinColumn(name = "rds_dbinstance_parameter_group_id", nullable = false)
	private RdsDbparameterGroup rdsParameterGroup;

	private String replicationUserName;

	private String replicationPassword;

	public RdsDbinstance() {
		securityGroups = new ArrayList<RdsDbsecurityGroup>();
		read_only = false;
	}

	public RdsDbinstance(final AccountBean account,
			final RdsDbparameterGroup rdsParameterGroup) {
		this();
		this.account = account;
		this.rdsParameterGroup = rdsParameterGroup;
	}

	public AccountBean getAccount() {
		return account;
	}

	public String getAddress() {
		return address;
	}

	public Integer getAllocatedStorage() {
		return allocatedStorage;
	}

	public Boolean getAllowMajorVersionUpgrade() {
		return allowMajorVersionUpgrade;
	}

	public Boolean getAutoMinorVersionUpgrade() {
		return autoMinorVersionUpgrade;
	}

	public String getAvailabilityZone() {
		return availabilityZone;
	}

	public Integer getBackupRetentionPeriod() {
		return backupRetentionPeriod;
	}

	public String getDbinstanceClass() {
		return dbinstanceClass;
	}

	public String getDbinstanceId() {
		return dbinstanceId;
	}

	public String getDbinstanceStatus() {
		return dbinstanceStatus;
	}

	public String getDbName() {
		return dbName;
	}

	public String getDbParameterGroup() {
		return dbParameterGroup;
	}

	public String getDbParameterGroupStatus() {
		return dbParameterGroupStatus;
	}

	public long getDbParameterGroupUserId() {
		return dbParameterGroupUserId;
	}

	public String getEngine() {
		return engine;
	}

	public String getEngineVersion() {
		return engineVersion;
	}

	public String getFinalSnapshotId() {
		return finalSnapshotId;
	}

	public long getId() {
		return id;
	}

	public Date getInstanceCreateTime() {
		return instanceCreateTime;
	}

	public String getInstanceId() {
		return instanceId;
	}

	public String getInternalIP() {
		return internalIP;
	}

	public Date getLatestRestorableTime() {
		return latestRestorableTime;
	}

	public String getLicenseModel() {
		return licenseModel;
	}

	public String getMasterUsername() {
		return masterUsername;
	}

	public String getMasterUserPassword() {
		return masterUserPassword;
	}

	public Boolean getMultiAz() {
		return multiAz;
	}

	public List<RdsParameter> getPendingRebootParameters() {
		return pendingRebootParameters;
	}

	public Integer getPort() {
		return port;
	}

	public String getPreferredBackupWindow() {
		return preferredBackupWindow;
	}

	public String getPreferredMaintenanceWindow() {
		return preferredMaintenanceWindow;
	}

	public RdsDbparameterGroup getRdsParameterGroup() {
		return rdsParameterGroup;
	}

	public Boolean getRead_only() {
		return read_only;
	}

	public List<String> getReplicas() {
		return replicas;
	}

	public String getReplicationPassword() {
		return replicationPassword;
	}

	public String getReplicationUserName() {
		return replicationUserName;
	}

	public String getSecurityGroup() {
		return securityGroup;
	}

	public String getSecurityGroupId() {
		return securityGroupId;
	}

	public List<RdsDbsecurityGroup> getSecurityGroups() {
		return securityGroups;
	}

	public String getSnapshotId() {
		return snapshotId;
	}

	public String getSourceDbinstanceId() {
		return sourceDbinstanceId;
	}

	public long getUserId() {
		return userId;
	}

	public String getVolumeId() {
		return volumeId;
	}

	public void setAccount(final AccountBean account) {
		this.account = account;
	}

	public void setAddress(final String address) {
		this.address = address;
	}

	public void setAllocatedStorage(final Integer allocatedStorage) {
		this.allocatedStorage = allocatedStorage;
	}

	public void setAllowMajorVersionUpgrade(
			final Boolean allowMajorVersionUpgrade) {
		this.allowMajorVersionUpgrade = allowMajorVersionUpgrade;
	}

	public void setAutoMinorVersionUpgrade(final Boolean autoMinorVersionUpgrade) {
		this.autoMinorVersionUpgrade = autoMinorVersionUpgrade;
	}

	public void setAvailabilityZone(final String availabilityZone) {
		this.availabilityZone = availabilityZone;
	}

	public void setBackupRetentionPeriod(final Integer backupRetentionPeriod) {
		this.backupRetentionPeriod = backupRetentionPeriod;
	}

	public void setDbinstanceClass(final String dbinstanceClass) {
		this.dbinstanceClass = dbinstanceClass;
	}

	public void setDbinstanceId(final String dbinstanceId) {
		this.dbinstanceId = dbinstanceId;
	}

	public void setDbinstanceStatus(final String dbinstanceStatus) {
		this.dbinstanceStatus = dbinstanceStatus;
	}

	public void setDbName(final String dbName) {
		this.dbName = dbName;
	}

	public void setDbParameterGroup(final String dbParameterGroup) {
		this.dbParameterGroup = dbParameterGroup;
	}

	public void setDbParameterGroupStatus(final String dbParameterGroupStatus) {
		this.dbParameterGroupStatus = dbParameterGroupStatus;
	}

	public void setDbParameterGroupUserId(final long dbParameterGroupUserId) {
		this.dbParameterGroupUserId = dbParameterGroupUserId;
	}

	public void setEngine(final String engine) {
		this.engine = engine;
	}

	public void setEngineVersion(final String engineVersion) {
		this.engineVersion = engineVersion;
	}

	public void setFinalSnapshotId(final String finalSnapshotId) {
		this.finalSnapshotId = finalSnapshotId;
	}

	public void setId(final long id) {
		this.id = id;
	}

	public void setInstanceCreateTime(final Date instanceCreateTime) {
		this.instanceCreateTime = instanceCreateTime;
	}

	public void setInstanceId(final String instanceId) {
		this.instanceId = instanceId;
	}

	public void setInternalIP(final String internalIP) {
		this.internalIP = internalIP;
	}

	public void setLatestRestorableTime(final Date latestRestorableTime) {
		this.latestRestorableTime = latestRestorableTime;
	}

	public void setLicenseModel(final String licenseModel) {
		this.licenseModel = licenseModel;
	}

	public void setMasterUsername(final String masterUsername) {
		this.masterUsername = masterUsername;
	}

	public void setMasterUserPassword(final String masterUserPassword) {
		this.masterUserPassword = masterUserPassword;
	}

	public void setMultiAz(final Boolean multiAz) {
		this.multiAz = multiAz;
	}

	public void setPendingRebootParameters(
			final List<RdsParameter> pendingRebootParameters) {
		this.pendingRebootParameters = pendingRebootParameters;
	}

	public void setPort(final Integer port) {
		this.port = port;
	}

	public void setPreferredBackupWindow(final String preferredBackupWindow) {
		this.preferredBackupWindow = preferredBackupWindow;
	}

	public void setPreferredMaintenanceWindow(
			final String preferredMaintenanceWindow) {
		this.preferredMaintenanceWindow = preferredMaintenanceWindow;
	}

	public void setRdsParameterGroup(final RdsDbparameterGroup rdsParameterGroup) {
		this.rdsParameterGroup = rdsParameterGroup;
	}

	public void setRead_only(final Boolean read_only) {
		this.read_only = read_only;
	}

	public void setReplicas(final List<String> replicas) {
		this.replicas = replicas;
	}

	public void setReplicationPassword(final String pw) {
		replicationPassword = pw;
	}

	public void setReplicationUserName(final String un) {
		replicationUserName = un;
	}

	public void setSecurityGroup(final String securityGroup) {
		this.securityGroup = securityGroup;
	}

	public void setSecurityGroupId(final String securityGroupId) {
		this.securityGroupId = securityGroupId;
	}

	public void setSecurityGroups(final List<RdsDbsecurityGroup> securityGroups) {
		this.securityGroups = securityGroups;
	}

	public void setSnapshotId(final String snapshotId) {
		this.snapshotId = snapshotId;
	}

	public void setSourceDbinstanceId(final String sourceDbinstanceId) {
		this.sourceDbinstanceId = sourceDbinstanceId;
	}

	public void setUserId(final long userId) {
		this.userId = userId;
	}

	public void setVolumeId(final String volumeId) {
		this.volumeId = volumeId;
	}

}
