package com.msi.tough.model.rds;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated May 10, 2011 9:13:49 AM by Hibernate Tools 3.4.0.CR1

/**
 * RdsPendingModifiedValues generated by hbm2java
 */

@Entity
@Table(name = "rds_pending_values")
public class RdsPendingModifiedValues {

	private String dbinstanceId;
	private String userId;
	private Integer allocatedStorage;
	private Integer backupRetentionPeriod;
	private String dbinstanceClass;
	private String engineVersion;
	private String masterUserPassword;
	private Boolean multiAz;
	private Integer port;

	public Integer getAllocatedStorage() {
		return allocatedStorage;
	}

	public Integer getBackupRetentionPeriod() {
		return backupRetentionPeriod;
	}

	public String getDbinstanceClass() {
		return dbinstanceClass;
	}

	public String getDbinstanceId() {
		return dbinstanceId;
	}

	public String getEngineVersion() {
		return engineVersion;
	}

	public String getMasterUserPassword() {
		return masterUserPassword;
	}

	public Boolean getMultiAz() {
		return multiAz;
	}

	public Integer getPort() {
		return port;
	}

	public String getUserId() {
		return userId;
	}

	public void setAllocatedStorage(Integer allocatedStorage) {
		this.allocatedStorage = allocatedStorage;
	}

	public void setBackupRetentionPeriod(Integer backupRetentionPeriod) {
		this.backupRetentionPeriod = backupRetentionPeriod;
	}

	public void setDbinstanceClass(String dbinstanceClass) {
		this.dbinstanceClass = dbinstanceClass;
	}

	public void setDbinstanceId(String dbinstanceId) {
		this.dbinstanceId = dbinstanceId;
	}

	public void setEngineVersion(String engineVersion) {
		this.engineVersion = engineVersion;
	}

	public void setMasterUserPassword(String masterUserPassword) {
		this.masterUserPassword = masterUserPassword;
	}

	public void setMultiAz(Boolean multiAz) {
		this.multiAz = multiAz;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
