package com.msi.tough.model.rds;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RdsReservedDbinstance generated by hbm2java
 */

@Entity
@Table(name = "rds_reserved_dbinstance")
public class RdsReservedDbinstance {

	private String reservedDbinstanceId;
	private String userId;
	private String reservedDbinstanceOfferingId;
	private Integer dbinstanceCount;
	private Date startTime;
	private String status;

	public Integer getDbinstanceCount() {
		return dbinstanceCount;
	}

	public String getReservedDbinstanceId() {
		return reservedDbinstanceId;
	}

	public String getReservedDbinstanceOfferingId() {
		return reservedDbinstanceOfferingId;
	}

	public Date getStartTime() {
		return startTime;
	}

	public String getStatus() {
		return status;
	}

	public String getUserId() {
		return userId;
	}

	public void setDbinstanceCount(Integer dbinstanceCount) {
		this.dbinstanceCount = dbinstanceCount;
	}

	public void setReservedDbinstanceId(String reservedDbinstanceId) {
		this.reservedDbinstanceId = reservedDbinstanceId;
	}

	public void setReservedDbinstanceOfferingId(
			String reservedDbinstanceOfferingId) {
		this.reservedDbinstanceOfferingId = reservedDbinstanceOfferingId;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
